# Generated by Django 4.0.1 on 2023-07-16 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clims',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callback_id', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('repo', models.CharField(max_length=255)),
                ('template_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('company_email', models.CharField(max_length=255)),
                ('company_number', models.CharField(max_length=255)),
                ('company_linkedin', models.CharField(max_length=255)),
                ('company_location', models.CharField(max_length=255)),
                ('company_bio', models.TextField(default='the bio not filled yet.')),
                ('start_year', models.PositiveIntegerField()),
                ('no_of_emp', models.PositiveIntegerField()),
                ('logo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ind_Profile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('profile_bio', models.TextField(default='the bio not filled yet.')),
                ('contact_number', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('skills', models.CharField(max_length=255)),
                ('resume_image', models.CharField(max_length=255)),
                ('usr_type', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Individual Profiles',
            },
        ),
        migrations.CreateModel(
            name='JobCreate',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField(default='the description not filled yet.')),
                ('experience', models.CharField(max_length=255)),
                ('looking_for', models.CharField(max_length=255)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('environment', models.TextField()),
                ('company_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='backend.companydetails')),
            ],
            options={
                'verbose_name_plural': 'Job Creates',
            },
        ),
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('tech', 'Technical'), ('non-tech', 'Non-Technical')], default='tech', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField()),
                ('github', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Social Links',
            },
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('userid', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StackReq',
            fields=[
                ('stackid', models.IntegerField(primary_key=True, serialize=False)),
                ('skills', models.TextField()),
                ('job_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stack_requirements', to='backend.jobcreate')),
            ],
            options={
                'verbose_name_plural': 'Stack Requirements',
            },
        ),
        migrations.CreateModel(
            name='Rec_Profile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('profile_bio', models.TextField(default='the bio not filled yet.')),
                ('contact_number', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('linked_in', models.CharField(max_length=255)),
                ('no_of_emp', models.CharField(max_length=255)),
                ('start_date', models.CharField(max_length=255)),
                ('logo', models.CharField(max_length=255)),
                ('company_data', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.companydetails')),
            ],
            options={
                'verbose_name_plural': 'Recruiter Profiles',
            },
        ),
        migrations.CreateModel(
            name='Applyed_jobs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
                ('job_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='backend.jobcreate')),
            ],
            options={
                'verbose_name_plural': 'Applied Jobs',
            },
        ),
    ]
