# Generated by Django 4.1.9 on 2023-06-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ind_profile',
            name='contact_number',
            field=models.CharField(default='sample', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ind_profile',
            name='location',
            field=models.CharField(default='sampe1', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ind_profile',
            name='usr_type',
            field=models.CharField(default='sample2', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ind_profile',
            name='resume_image',
            field=models.CharField(max_length=255),
        ),
    ]
