# Generated by Django 4.1.9 on 2023-06-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clims',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callback_id', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('repo', models.CharField(max_length=255)),
                ('template_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data', models.BinaryField()),
            ],
        ),
        migrations.RenameField(
            model_name='rec_profile',
            old_name='first_name',
            new_name='contact_number',
        ),
        migrations.RenameField(
            model_name='rec_profile',
            old_name='last_name',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='rec_profile',
            name='description',
        ),
        migrations.AddField(
            model_name='ind_profile',
            name='contact_number',
            field=models.CharField(default=5455, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ind_profile',
            name='location',
            field=models.CharField(default='wefds', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ind_profile',
            name='userid',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ind_profile',
            name='usr_type',
            field=models.CharField(default='vwsd', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rec_profile',
            name='linked_in',
            field=models.CharField(default='sdvv', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rec_profile',
            name='location',
            field=models.CharField(default='advsdv', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rec_profile',
            name='logo',
            field=models.CharField(default='sdv dv s', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rec_profile',
            name='name',
            field=models.CharField(default='advvz', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rec_profile',
            name='no_of_emp',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rec_profile',
            name='start_date',
            field=models.CharField(default='1sdv', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rec_profile',
            name='userid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ind_profile',
            name='resume_image',
            field=models.CharField(max_length=255),
        ),
    ]
